name: Lint from a push (only diff)

# on: push

env:
  DBT_PROFILE_TARGET:            test

jobs:
  lint_for_diffs_on_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR by removing the merge into main
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: List all the remote branches
      run: git branch -r
    
    - name: List all the local branches
      run: git branch
      
    - run: |
        git fetch origin main
        git branch
        git checkout main
        git log -20
        cat ./models/marts/core/fct_orders.sql
        git checkout ${{ github.event.pull_request.head.sha }}
        git checkout feature/sqlfluff_lint_fix2
      # with:
      #   fetch-depth: '0'
        # ref: ${{ github.event.pull_request.head.sha }}
      
    
    # - name: git branch temp setup
    #   run: |
    #     git config --global user.email "temp_branch@example.com"
    #     git config --global user.name "temp_branch"
    #     git checkout -b temp
    #     git add .
    #     git commit -am "temp branch of pr"

    - name: git branch temp setup
      run: |
        git branch
        git log -20

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}

    - name: event info
      run: |
        jq . $GITHUB_EVENT_PATH

    # - name: fetch main branch for sqlfluff to compare
    #   run: |
    #     git fetch origin main:main  
    #     git branch
    #     git log -20

    # - name: DELETE this step
    #   run: |
    #     git checkout main  
    #     git branch
    #     git log -20

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake==0.19.1
        pip install sqlfluff==0.4.0

    - name: Lint SQL
      run: |
        diff-quality --violations sqlfluff --compare-branch main

    - name: check pr
      run: |
        cat ./models/marts/core/fct_orders.sql

    - name: check pr status
      run: |
        git status
        git add .
    
    - name: Lint SQL 2
      run: |
        diff-quality --violations sqlfluff --compare-branch main

    
    - name: check main
      run: |
        git checkout main
        cat ./models/marts/core/fct_orders.sql
    
    - name: check again feature/sqlfluff_lint_fix2
      run: |
        git checkout feature/sqlfluff_lint_fix2
        diff-quality --violations sqlfluff --compare-branch origin/main
    
    - name: check again feature/sqlfluff_lint_fix2 sqlfluff
      run: |
        sqlfluff lint
