name: dbt-sqlfluff-env
channels:
  - conda-forge
  - defaults
dependencies:
  - agate=1.6.1
  - pip
  - python=3.8
  - pip:
    - dbt==1.0.0
    - sqlfluff==0.9.0
    - sqlfluff-templater-dbt==0.9.0
    # Alternatively, to use latest SQLFluff updates from master. USE WITH CAUTION
    # - "git+https://github.com/sqlfluff/sqlfluff.git@master#egg=sqlfluff"