name: Test Production Data Quality

on:
  schedule:
    - cron:  '0 1 * * *' # Run every day at 1am
  workflow_dispatch:


env:
  DBT_PROFILE_TARGET:            prod
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_PROD_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_PROD_PASSWORD }}
  DBT_PROFILE_ROLE:              DBT_CLOUD
  DBT_PROFILE_DB:                ANALYTICS_TPCH_ADMIN
  DBT_PROFILE_SCHEMA:            STAGING
  DBT_PROFILE_WH:                PROCESSING_WH

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install DBT
      run: |
        python -m pip install --upgrade pip
        pip install dbt==1.0.0
        dbt deps
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        role-duration-seconds: 1200
        role-session-name: MySessionName

    - name: Deploy
      run: |
        dbt test --profiles-dir ./ci_profiles


        


    